/* CRIA A TABELA DE USU�RIO */
CREATE TABLE USUARIO (
    ID_USUARIO INT IDENTITY(1,1),
    NOME VARCHAR(30),
    DESCRICAO VARCHAR(300),
    SENHA VARCHAR(30),
    TIPO VARCHAR(30),
    CADASTRO DATE,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);

/* CRIA A TABELA DE EMPRESA */
CREATE TABLE EMPRESA (
    ID_EMPRESA INT IDENTITY(1,1),
    RAZAO_SOCIAL VARCHAR(30),
    DESCRICAO VARCHAR(30),
    N_FANTASIA VARCHAR(30),
    ENDERECO VARCHAR(30),
    cep varchar(14),
    NUMERO INT,
    BAIRRO VARCHAR(30),
    CIDADE VARCHAR(30),
    UF CHAR(2),
    TELEFONE VARCHAR(15),
    CNPJ VARCHAR(20),
    EMAIL VARCHAR(30),
    foto image,
    CADASTRO DATE,
    CONSTRAINT PK_EMPRESA PRIMARY KEY (ID_EMPRESA)
);

/* CRIA A TABELA DE FORNECEDORES */
CREATE TABLE FORNECEDOR (
    ID_FORNECEDOR INT IDENTITY(1,1),
    NOME VARCHAR(30),
    ENDERECO VARCHAR(30),
    NUMERO INT,
    BAIRRO VARCHAR(30),
    CIDADE VARCHAR(30),
    UF CHAR(2),
    CEP VARCHAR(16),
    TELEFONE VARCHAR(16),
    CNPJ VARCHAR(20),
    EMAIL VARCHAR(30),
    CADASTRO DATE,
    CONSTRAINT PK_FORNECEDOR PRIMARY KEY (ID_FORNECEDOR)
);

/* CRIA A TABELA DE CLIENTES */
CREATE TABLE CLIENTE (
    ID_CLIENTE INT IDENTITY(1,1),
    NOME VARCHAR(30),
    ENDERECO VARCHAR(30),
    NUMERO INT,
    BAIRRO VARCHAR(30),
    CIDADE VARCHAR(30),
    UF CHAR(2),
    CEP VARCHAR(16),
    TELEFONE VARCHAR(16),
    CPF VARCHAR(16),
    EMAIL VARCHAR(30),
    CADASTRO DATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

/* CRIA A TABELA DE PRODUTOS */
CREATE TABLE PRODUTO (
    ID_PRODUTO INT IDENTITY(1,1),
    PRODUTO_DESCRICAO VARCHAR(30),
    ID_FORNECEDOR INT,
    VL_CUSTO DECIMAL(11,2),
    VL_VENDA DECIMAL(11,2),
    ESTOQUE DECIMAL(11,2),
    ESTOQUE_MIN DECIMAL(11,2),
    UNIDADE VARCHAR(6),
    CADASTRO DATE,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO),
    CONSTRAINT FK_FORNECEDOR_PRODUTO FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR)
);

/* CRIA A TABELA DE FORMA DE PAGAMENTO */
CREATE TABLE FORMA_PGTO (
    ID_FORMA_PGTO INT IDENTITY(1,1),
    DESCRICAO VARCHAR(30),
    CADASTRO DATE,
    CONSTRAINT PK_FORMA_PGTO PRIMARY KEY (ID_FORMA_PGTO)
);

/* CRIA A TABELA DE COMPRAS */
CREATE TABLE COMPRA (
    ID_COMPRA INT IDENTITY(1,1),
    ID_FORNECEDOR INT,
    ID_FORMA_PGTO INT,
    USUARIO VARCHAR(30),
    VALOR DECIMAL(11,2),
    CADASTRO DATE,
    CONSTRAINT PK_COMPRA PRIMARY KEY (ID_COMPRA),
    CONSTRAINT FK_FORNECEDOR_COMPRA FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR),
    CONSTRAINT FK_FORMA_PGTO_COMPRA FOREIGN KEY (ID_FORMA_PGTO) REFERENCES FORMA_PGTO(ID_FORMA_PGTO)
);

/* CRIA A TABELA DE ITENS DE COMPRA */
CREATE TABLE ITEM_COMPRA (
    ID_SEQUENCIA INT IDENTITY(1,1),
    ID_COMPRA INT,
    ID_PRODUTO INT,
    QTDE DECIMAL(11,2),
    VL_CUSTO DECIMAL(11,2),
    DESCONTO DECIMAL(11,2),
    TOTAL_ITEM DECIMAL(11,2),
    CONSTRAINT PK_ITEM_COMPRA PRIMARY KEY (ID_SEQUENCIA, ID_COMPRA),
    CONSTRAINT FK_COMPRA_ITEM_COMPRA FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA),
    CONSTRAINT FK_PRODUTO_ITEM_COMPRA FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO) ON DELETE CASCADE
);

/* CRIA A TABELA DE CONTAS A PAGAR */
CREATE TABLE CONTAS_PAGAR (
    ID_SEQUENCIA INT IDENTITY(1,1),
    ID_COMPRA INT,
    VALOR_PARCELA DECIMAL(11,2),
    DT_VENCIMENTO DATE,
    DT_PAGAMENTO DATE,
    ATRASO INT,
    JUROS DECIMAL(11,2),
    VL_JUROS DECIMAL(11,2),
    TOTAL_PAGAR DECIMAL(11,2),
    STATUS VARCHAR(30),
    CONSTRAINT PK_CONTAS_PAGAR PRIMARY KEY (ID_SEQUENCIA, ID_COMPRA),
    CONSTRAINT FK_COMPRA_CONTAS_PAGAR FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA) ON DELETE CASCADE
);

/* CRIA A TABELA DE VENDAS */
CREATE TABLE VENDA (
    ID_VENDA INT IDENTITY(1,1),
    ID_CLIENTE INT,
    ID_FORMA_PGTO INT,
    USUARIO VARCHAR(30),
    VALOR DECIMAL(11,2),
    CADASTRO DATE,
    CONSTRAINT PK_VENDA PRIMARY KEY (ID_VENDA),
    CONSTRAINT FK_CLIENTE_VENDA FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_FORMA_PGTO_VENDA FOREIGN KEY (ID_FORMA_PGTO) REFERENCES FORMA_PGTO(ID_FORMA_PGTO)
);

/* CRIA A TABELA DE ITENS DE VENDA */
CREATE TABLE ITEM_VENDA (
    ID_SEQUENCIA INT IDENTITY(1,1),
    ID_VENDA INT,
    ID_PRODUTO INT,
    QTDE DECIMAL(11,2),
    VL_CUSTO DECIMAL(11,2),
    DESCONTO DECIMAL(11,2),
    TOTAL_ITEM DECIMAL(11,2),
    CONSTRAINT PK_ITEM_VENDA PRIMARY KEY (ID_SEQUENCIA, ID_VENDA),
    CONSTRAINT FK_VENDA_ITEM_VENDA FOREIGN KEY (ID_VENDA) REFERENCES VENDA(ID_VENDA),
    CONSTRAINT FK_PRODUTO_ITEM_VENDA FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO) ON DELETE CASCADE
);

/* CRIA A TABELA DE CONTAS A RECEBER */
CREATE TABLE CONTAS_RECEBER (
    ID_SEQUENCIA INT IDENTITY(1,1),
    ID_VENDA INT,
    VALOR_PARCELA DECIMAL(11,2),
    DT_VENCIMENTO DATE,
    DT_PAGAMENTO DATE,
    ATRASO INT,
    JUROS DECIMAL(11,2),
    VL_JUROS DECIMAL(11,2),
    TOTAL_PAGAR DECIMAL(11,2),
    STATUS VARCHAR(30),
    CONSTRAINT PK_CONTAS_RECEBER PRIMARY KEY (ID_SEQUENCIA, ID_VENDA),
    CONSTRAINT FK_VENDA_CONTAS_RECEBER FOREIGN KEY (ID_VENDA) REFERENCES VENDA(ID_VENDA) ON DELETE CASCADE
);
